// Auto-generated by @thexjs/core -- do not edit
export type RouteMap = {
  "/settings": Record<string, never>;
  "/": Record<string, never>;
  "/project/:projectId": { projectId: string };
};

export function href<T extends keyof RouteMap & string>(
  path: T,
  ...[params]: RouteMap[T] extends Record<string, never> ? [] : [RouteMap[T]]
): string {
  if (!params) return path;
  let result: string = path;
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(`:${key}(?=/|$)`), encodeURIComponent(String(value)));
  }
  // Catch-all params have no `:name` token in the path — they render as an
  // anonymous `*` segment. Substitute them in segment order, keeping `/`
  // between encoded fragments so multi-segment values stay readable. An exact
  // segment-token check (prefixed by `/`) is required: a prefix scan of
  // `:key` would also match a longer `:id2` param and skip the wildcard.
  const isNamedToken = (key: string) => new RegExp(`(^|/):${key}(?=/|$)`).test(path);
  for (const [key, value] of Object.entries(params)) {
    if (!isNamedToken(key)) {
      const encoded = String(value)
        .split("/")
        .map(encodeURIComponent)
        .join("/");
      result = result.replace(/\*/, encoded);
    }
  }
  result = result.replace(/\*+$/, "");
  return result;
}
